### ISSUE TITLE
Conflict? math log() and debuging log()

### ISSUE THREAD

**Issue by z3dev** [jscad/scad-api#16]
Just wondering if these would conflict if used within a single script.

**Comment by bhouston** [comment]
You should have them both as members of their parent objects.  Thus Math.log() and Debugger.log() or something like that.

**Comment by bhouston** [comment]
BTW awesome contributions!

**Comment by kaosat-dev** [comment]
good point @z3dev ! and also spot on @bhouston :)
I really dislike that OpenJSCAD puts everything at a global level, in an implicit manner (explicit might be more verbose but it is so much better overall).
I think something like the following would indeed be preferable
```javascript 
const {Math, Debugger} = require('scad-api') //if not require, then something similar
const partSize = Math.log() * 42
```

but that would be a major breaking change (which I support, it would solve quite a few issues)

**Comment by bhouston** [comment]
ThreeJS also has a problem with a module named Math -- it caused problems when ThreeJS moved towards requires like in your example as opposed to always acccessing it like THREE.Math.  What happened is that it was renamed _Math.  I would have prefered MathUtils instead myself.

**Comment by kaosat-dev** [comment]
@bhouston yeah , just underscoring it , is not very explicit, almost makes it seem like a 'private variable' :) 
To our specific problem with Log : I just realised the 'log' that does ...loggging  is actually 'namespaced' to openjscad anyway, so no conflict: (ie you have to call openjscad.log).
I would argue that it means it should not be part of this repo but the main one, but for now it is not the end of the world.

**Comment by bhouston** [comment]
@kaosat-dev Sort of off topic, but are you finding CSG.js robust?  We did integrate it into Clara.io years ago but it was not robust in the least except for the simplest of problems.  Thus we never moved it out of "beta".  I guess with your investments in this tool set you believe it is now robust with your changes?

Have you tested it beyond just simple test cases?

**Comment by kaosat-dev** [comment]
@bhouston  I think I actually remember your posts about those experiments for Clara.io (always used to look out for your great new features/eye candy and wish it was in 'mainline' three.js already :) 

Do you mean geometric robustness or general usability as a lib?
We have not changed the CSG.js 'core' at all so far, so geometric robustness is still the same (though there have been lots of improvements over the years from what I have seen).
However , all this huge cleanup and reorganization , adding tests etc, was done because the next step (at least for me) is to tackle a in depth cleanup & upgrade (towards simplicity AND robustness) of CSG.js itself .
Good , manifold meshed are a must for 3d printing use (my main & only use tbh).

**Comment by z3dev** [comment]
Closing as this issue does not exist with V2 modeling.
