### ISSUE TITLE
Incoherent API between rectangular_extrude and other extrusions

### ISSUE THREAD

**Issue by kaosat-dev** [jscad/scad-api#34]
Currently `linear` & `rotate` extrude take **params** first, *2d shapes second*, while`rectangular_extrude` takes params `second` ! 
This is very confusing and incoherent , and needs to be changed (yes, BREAKING CHANGE !)
We want good, coherent and not confusing APIs, right @z3dev  ;) ?

**Comment by z3dev** [comment]
Agreed. The current API is totally confusing to anyone new.

I think you will find more as you start to create a new standard.

FYI, I'm not sure what is the "correct" API but this inconsistency has to be corrected.

I prefer an API that doesn't require an order to the arguments, which is why I prefer the CSG style of passing aguments as a attribute of an anonymous object. But I'll try to be flexible....

**Comment by kaosat-dev** [comment]
There are a few bad things, but still not quite as horrible as I feared (except for a few function where there are so many ways to specify params it is just frightening).

what do you mean by 
> CSG style of passing aguments as a attribute of an anonymous object

do you mean passing options like this ? 
```javascript 
{length: 10, round: true}
```

**Comment by z3dev** [comment]
Correct. By the way, I believe both CSG and SCAPAPI are inconsistent in the use of aguements, so the new API will be far better.

**Comment by kaosat-dev** [comment]
I really like object options like the above as well so we are good :) 
Yeah the api can only get better !

**Comment by z3dev** [comment]
V2 modeling passes options via anonymous objects.

These changes will not be supported as part of the SCAD compatibility layer.
